disabled_rules:
- cyclomatic_complexity
- file_length
- function_body_length
- function_parameter_count
- line_length
- nesting
- todo
- type_body_length
- unused_closure_parameter
opt_in_rules:
- attributes
attributes:
  always_on_line_above: ["@objc"]
large_tuple:
  warning: 4
  error: 4
