# This is a basic workflow to help you get started with Actions
name: Fetch Upstream

on: 
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Fetch upstream Action
        uses: 135e2/sync-upstream-repo@v0.1.5
        with:
        #Git upstream repo
         upstream_repo: https://github.com/signalapp/Signal-iOS.git
         upstream_branch: master
         local_branch: main
         github_token: ${{ secrets.PERSONAL_TOKEN }}

